sudo: false
language: php
php:
  - 5.6
  - 7.0
env:
  - CODECLIMATE_REPO_TOKEN=3828be099949ca0e668f1d43e1f364bd4aaf9d03618ddeca36d1b076c4c82e61

before_script:
  # UOPZ
  #- git clone https://github.com/krakjoe/uopz.git
  #- sh -c "cd uopz && phpize && ./configure && make && sudo make install"
  #- echo "extension=uopz.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

  - composer self-update
  - composer install

script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml tests
after_script: ./vendor/bin/test-reporter
